// movies
export const DISPATCH_TITLE = 'DISPATCH_TITLE';
export const DISPATCH_CURRENT_PAGE = 'DISPATCH_CURRENT_PAGE';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';
export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_MOVIE_DETAILS_ERROR = 'FETCH_MOVIE_DETAILS_ERROR';